/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames_Admin;

import Control.Control_Compra;
import Control.Control_Productos;
import Entidades.Compra;
import Entidades.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class FrmAdministarInventarioProductos extends javax.swing.JFrame {
private DefaultTableModel tableModel;
private int U;

    /**
     * Creates new form FrmAdministrarUsuarios
     */
    public FrmAdministarInventarioProductos() {
        initComponents();
        configurarTablaStock();
        cargarDatosStock();
    }

    public FrmAdministarInventarioProductos(int U) {
        initComponents();
        this.U = U;
        configurarTablaStock();
        cargarDatosStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoAdmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FondoAdmin1 = new javax.swing.JLabel();

        FondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/FondoAdmin.jpg"))); // NOI18N
        FondoAdmin.setInheritsPopupMenu(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Gestionar Inventario Productos");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });
        jPanel2.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        btnAgregar.setBackground(new java.awt.Color(51, 255, 0));
        btnAgregar.setText("Comprar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 31));

        btnEditar.setBackground(new java.awt.Color(255, 255, 0));
        btnEditar.setText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, 31));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, 31));

        jLabel1.setText("Editar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 547, 72, -1));

        jLabel2.setText("Agregar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 487, -1, -1));

        jLabel3.setText("Borrar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 619, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Seleccione un cliente...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 475, -1, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Modelo", "Cantidad Stock"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 510, 270));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 90, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 60, -1));

        FondoAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/FondoAdmin.jpg"))); // NOI18N
        FondoAdmin1.setInheritsPopupMenu(false);
        jPanel1.add(FondoAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
         FrmMenuAdmin fma = new FrmMenuAdmin(U);
        fma.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    int row = tblProductos.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!validarCantidad()) {
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de aumentar el stock en " + txtCantidad.getText() + " unidades?", 
        "Confirmar compra", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    int id = (int) tableModel.getValueAt(row, 0);
    int cantidad = Integer.parseInt(txtCantidad.getText());
    
    try {
        Control_Compra cc = new Control_Compra();
        Control_Productos cp = new Control_Productos();
        // 1. Primero aumentamos el stock (como ya lo tienes)
        cp.aumentarStockSP(id, cantidad);
        //Registramos compra
        Compra c = new Compra(id, U, cantidad, id);
        cc.registrarCompra(c);
        cargarDatosStock();
        JOptionPane.showMessageDialog(this, "Stock actualizado exitosamente");
        txtCantidad.setText("");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar stock: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int row = tblProductos.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de poner el stock a 0?", 
        "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    int id = (int) tableModel.getValueAt(row, 0);
    
    try {
        Control_Productos cp = new Control_Productos();
        cp.actualizarStock(id, 0);
        cargarDatosStock();
        JOptionPane.showMessageDialog(this, "Stock eliminado (puesto a 0) exitosamente");
        txtCantidad.setText("");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar stock: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int row = tblProductos.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Selecciona un producto", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!validarCantidad()) {
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de modificar el stock a " + txtCantidad.getText() + " unidades?", 
        "Confirmar modificación", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    int id = (int) tableModel.getValueAt(row, 0);
    int nuevaCantidad = Integer.parseInt(txtCantidad.getText());
    
    try {
        Control_Productos cp = new Control_Productos();
        cp.actualizarStock(id, nuevaCantidad);
        cargarDatosStock();
        JOptionPane.showMessageDialog(this, "Stock modificado exitosamente");
        txtCantidad.setText("");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al modificar stock: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed
private void configurarTablaStock() {
    tableModel = new DefaultTableModel();
    tableModel.addColumn("ID");      // Nueva columna
    tableModel.addColumn("Producto");
    tableModel.addColumn("Modelo");
    tableModel.addColumn("Stock");
    tblProductos.setModel(tableModel); 
}
    
private void cargarDatosStock() {
    try {
        Control_Productos cp = new Control_Productos();
        java.util.List<Producto> productos =  cp.listarProductosStock();
        tableModel.setRowCount(0); // Limpiar tabla
        
        for (Producto p : productos) {
            Object[] row = {
                p.getId(),       // ID al principio
                p.getProducto(),
                p.getModelo(),
                p.getCantidadStock()
            };
            tableModel.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
    }
}

private boolean validarCantidad() {
    String cantidadStr = txtCantidad.getText().trim();
    
    if (cantidadStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La cantidad no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    if (!cantidadStr.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "La cantidad solo puede contener números positivos", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    try {
        int cantidad = Integer.parseInt(cantidadStr);
        
        if (cantidad > 1000000) {
            JOptionPane.showMessageDialog(this, "La cantidad no puede ser mayor a 1,000,000", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
        
    } catch (NumberFormatException e) {
        // Esto solo ocurriría si el número es demasiado grande para un int
        JOptionPane.showMessageDialog(this, "La cantidad excede el límite permitido", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAdmin;
    private javax.swing.JLabel FondoAdmin1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
