/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames_Admin;

import Control.Control_Usuario;
import Entidades.Usuario;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class FrmAdministrarUsuarios extends javax.swing.JFrame {
    private int U;
    private Usuario usuario;
    private DefaultTableModel tableModel;

    /**
     * Creates new form FrmAdministrarUsuarios
     */
    public FrmAdministrarUsuarios(int U) {
        this.U=U;
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoAdmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAgregar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        FondoAdmin1 = new javax.swing.JLabel();

        FondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/FondoAdmin.jpg"))); // NOI18N
        FondoAdmin.setInheritsPopupMenu(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Gestionar Clientes");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 6, -1, -1));

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/esquema-de-boton-circular-de-flecha-hacia-atras-izquierda.png"))); // NOI18N
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });
        jPanel2.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Usuario", "Correo", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 530, 320));

        btnAgregar1.setBackground(new java.awt.Color(51, 255, 0));
        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 31));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 0));
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, 31));

        btnEliminar1.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, 31));

        FondoAdmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/FondoAdmin.jpg"))); // NOI18N
        FondoAdmin1.setInheritsPopupMenu(false);
        jPanel1.add(FondoAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        FrmMenuAdmin fma = new FrmMenuAdmin(U);
        fma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        FrmAgregarUsuario fma = new FrmAgregarUsuario(U);
        fma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        Control_Usuario cu = new Control_Usuario();
    int row = tblClientes.getSelectedRow();  // Obtén la fila seleccionada

    if (row >= 0) {
        // Obtener el valor del ID, que puede ser Long o Integer
        Object idObject = tblClientes.getValueAt(row, 0);  // Obtener el valor del ID en la primera columna

        // Verificar si idObject no es null y es del tipo esperado
        if (idObject != null) {
            int id;
            if (idObject instanceof Long) {
                id = ((Long) idObject).intValue();
            } else if (idObject instanceof Integer) {
                id = (int) idObject;
            } else {
                // Si el valor no es ni Long ni Integer, manejar el error
                JOptionPane.showMessageDialog(null, "El valor del ID no es válido.");
                return;
            }

            // Obtener los datos del usuario con el ID
            Usuario usuario = cu.obtenerUsuario(id);
            
            if (usuario != null) {
                // Crear la instancia del formulario de edición y cargar los datos
                FrmEditarUsuario fre = new FrmEditarUsuario(usuario, U);
                fre.setVisible(true);
                this.dispose();
            } else {
                // Si no se encuentra el usuario
                JOptionPane.showMessageDialog(null, "Usuario no encontrado.");
            }
        } else {
            // Si el valor del ID es null
            JOptionPane.showMessageDialog(null, "El ID del usuario no está disponible.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione un usuario para editar.");
    }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        Control_Usuario cu = new Control_Usuario();
        int row = tblClientes.getSelectedRow();  // Obtén la fila seleccionada

        if (row >= 0) {
            // Obtener el valor del ID, que puede ser Long o Integer
            Object idObject = tblClientes.getValueAt(row, 0);  // Obtener el valor del ID en la primera columna

            int id = (idObject instanceof Long) ? ((Long) idObject).intValue() : (int) idObject; // Convertir a int si es necesario

            // Llamar al método de eliminación
            cu.eliminarUsuario(id);
            cargarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un usuario para eliminar.");
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void cargarDatos() {
        try {
            java.util.List<Usuario> usuarios = new java.util.ArrayList<>();
            Control_Usuario cu = new Control_Usuario();
            usuarios = cu.listarUsuarios();
            tableModel.setRowCount(0); // Limpiar tabla

            for (Usuario u : usuarios) {
                Object[] row = {
                    u.getId(),
                    u.getNombreCompleto(),
                    u.getNombreUsuario(),
                    u.getDireccion(),
                    u.getCorreo()
                };
                tableModel.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }
    }

    private void configurarTabla() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Usuario");
        tableModel.addColumn("Correo");
        tableModel.addColumn("Dirección");
        tblClientes.setModel(tableModel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAdmin;
    private javax.swing.JLabel FondoAdmin1;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
